


export const SET_NAME = 'SET_NAME';
export const SET_LOCATION = 'SET_LOCATION';
export const ERROR_LOCATION = 'ERROR_LOCATION';
export const GET_INPUT = 'GET_INPUT';
export const TOGGLE_SEARCH_RESULT = 'TOGGLE_SEARCH_RESULT';
export const GET_ADDRESS_PREDICTIONS = 'GET_ADDRESS_PREDICTIONS';
